#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99

CONF=/etc/udptunnel/config.json
EXEC=/usr/bin/udptunnel

start_service() {
  procd_open_instance
  procd_set_param command $EXEC $CONF
  procd_set_param file $CONF
  procd_set_param pidfile /var/run/udptunnel.pid
  procd_set_param respawn
  procd_close_instance
}

start() {
        service_start $EXEC
}

stop() {
        service_stop $EXEC
}

reload() {
        service_reload $EXEC
}
